// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful'
import type { Document } from '@contentful/rich-text-types'

export interface IAuteurFields {
  /** Nom */
  nom?: string | undefined,

  /** Prénom */
  prenom: string,

  /** Structure */
  structure?: string | undefined,

  /** Bio */
  bio?: string | undefined,

  /** Email */
  email: string,

  /** Téléphone */
  telephone?: string | undefined,

  /** Site Web */
  siteWeb?: string | undefined,

  /** Photo */
  photo?: Asset | undefined,
}

export interface IAuteur extends Entry<IAuteurFields> {
  sys: {
    id: string,
    type: string,
    createdAt: string,
    updatedAt: string,
    locale: string,
    contentType: {
      sys: {
        id: 'auteur',
        linkType: 'ContentType',
        type: 'Link',
      },
    },
  },
}

export interface ICategorieFields {
  /** Titre */
  titre?: string | undefined,

  /** Identifiant */
  slug: string,

  /** Illustration */
  illustration: Asset,

  /** Description */
  description?: string | undefined,
}

export interface ICategorie extends Entry<ICategorieFields> {
  sys: {
    id: string,
    type: string,
    createdAt: string,
    updatedAt: string,
    locale: string,
    contentType: {
      sys: {
        id: 'categorie',
        linkType: 'ContentType',
        type: 'Link',
      },
    },
  },
}

export interface IFicheFields {
  /** Titre */
  titre: string,

  /** Identifiant */
  slug: string,

  /** Illustration */
  illustration: Asset,

  /** Description */
  description: string,

  /** Contenu */
  contenu: Document,

  /** Auteur */
  auteur: IAuteur,

  /** Date de publication */
  date: string,

  /** Tags */
  tags: string[],

  /** Structures */
  structures?: Entry<{ [fieldId: string]: unknown }>[] | undefined,
}

export interface IFiche extends Entry<IFicheFields> {
  sys: {
    id: string,
    type: string,
    createdAt: string,
    updatedAt: string,
    locale: string,
    contentType: {
      sys: {
        id: 'fiche',
        linkType: 'ContentType',
        type: 'Link',
      },
    },
  },
}

export interface IStructureFields {
  /** Nom */
  nom: string,

  /** Description */
  description?: string | undefined,

  /** Spécialités */
  specialites?: string[] | undefined,

  /** Adresse */
  adresse: { lat: number, lon: number },

  /** Site web */
  siteWeb?: string | undefined,

  /** Téléphone */
  telephone?: string | undefined,

  /** Email */
  email: string,
}

export interface IStructure extends Entry<IStructureFields> {
  sys: {
    id: string,
    type: string,
    createdAt: string,
    updatedAt: string,
    locale: string,
    contentType: {
      sys: {
        id: 'structure',
        linkType: 'ContentType',
        type: 'Link',
      },
    },
  },
}

export type CONTENT_TYPE = 'auteur' | 'categorie' | 'fiche' | 'structure';

export type LOCALE_CODE = 'fr';

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'fr';
