// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IAuteurFields {
  /** Nom */
  nom: string;

  /** Prénom */
  prenom: string;

  /** Photo */
  photo: Asset;

  /** Titre */
  titre: string;

  /** Structure */
  structure: string;

  /** Bio */
  bio?: string | undefined;

  /** Email */
  email: string;

  /** Téléphone */
  telephone?: string | undefined;

  /** Site Web */
  siteWeb?: string | undefined;

  /** Masculin ou féminin ? */
  femme: boolean;
}

export interface IAuteur extends Entry<IAuteurFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "auteur";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IFicheFields {
  /** Titre */
  titre: string;

  /** Identifiant */
  slug: string;

  /** Catégorie */
  categorie: "sante" | "besoins-primaires" | "social" | "interpretariat";

  /** Illustration */
  illustration: Asset;

  /** Description */
  description: string;

  /** Résumé */
  resume: Document;

  /** Contenu */
  contenu: Document;

  /** Auteur */
  auteur: IAuteur;

  /** Tags */
  tags: string[];

  /** Structures */
  structures?: IStructure[] | undefined;

  /** Pour aller plus loin */
  pourEnSavoirPlus?: ILien[] | undefined;

  /** Quelques Outils */
  outils?: ILien[] | undefined;

  /** Pour les patients */
  patients?: ILien[] | undefined;
}

export interface IFiche extends Entry<IFicheFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "fiche";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ILienFields {
  /** Titre */
  titre: string;

  /** Url */
  url?: string | undefined;

  /** Fichier */
  fichier?: Asset | undefined;
}

export interface ILien extends Entry<ILienFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "lien";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IStructureFields {
  /** Nom */
  nom: string;

  /** Description */
  description?: string | undefined;

  /** Spécialités */
  specialites?: string[] | undefined;

  /** Adresse */
  adresse: { lat: number; lon: number };

  /** Site web */
  siteWeb?: string | undefined;

  /** Téléphone */
  telephone?: string | undefined;

  /** Email */
  email: string;
}

export interface IStructure extends Entry<IStructureFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "structure";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE = "auteur" | "fiche" | "lien" | "structure";

export type LOCALE_CODE = "fr";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "fr";
