name: Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checks:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v22
      uses: actions/setup-node@v2
      with:
        node-version: 22
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install
    - name: Type checking
      run: yarn typecheck
    - name: Lint
      run: yarn lint
